### ISSUE TITLE
Replace text input with drop-down menu

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#1]
In the   [Weather-App](https://github.com/Shweta2024/JavaScript-Projects/tree/main/Weather-App) replace the text input of the city name with a drop-down menu which will have the name of all the cities that the user can select to view the weather report.

**Comment by SattyamSamania** [comment]
Hey @Shweta2024 please assign this issue to me under KWOC

**Comment by Shweta2024** [comment]
> Hey @Shweta2024 please assign this issue to me under KWOC

Make sure to complete the issue within a week & make a pr to the master branch.

**Comment by SattyamSamania** [comment]
@Shweta2024 Can I add 1 particular state's  cities?

**Comment by nazmus-saqib008** [comment]
Hey @Shweta2024 , i am eager to do solve this issue. If this job can't be done by @SattyamSamania , please make sure to assign me this task.

**Comment by Shweta2024** [comment]
> 

all the contributors are given a week to complete the pr and if they fail to complete it within a week or if they quit working on the issue, then only I'll assign it to someone else.
Till that time let him try to solve the issue.

**Comment by Shweta2024** [comment]
> Hey @Shweta2024 , i am eager to do solve this issue. If this job can't be done by @SattyamSamania , please make sure to assign me this task.
@nazmus-saqib008 
all the contributors are given a week to complete the pr and if they fail to complete it within a week or if they quit working on the issue, then only I'll assign it to someone else.
Till that time let him try to solve the issue.

**Comment by Shweta2024** [comment]
> Hey @Shweta2024 , i am eager to do solve this issue. If this job can't be done by @SattyamSamania , please make sure to assign me this task.

@nazmus-saqib008
all the contributors are given a week to complete the pr and if they fail to complete it within a week or if they quit working on the issue, then only I'll assign it to someone else.
Till that time let him try to solve the issue.

**Comment by Shweta2024** [comment]
@SattyamSamania  it's been a week, please complete your task by today.

**Comment by SattyamSamania** [comment]
> @SattyamSamania  it's been a week, please complete your task by today.

Hey @Shweta2024 I have made a PR. You can review it.
