### ISSUE TITLE
Alarm Clock 

### ISSUE THREAD

**Issue by Riya14-dangra** [Shweta2024/JavaScript-Projects#102]
**Describe the changes you'd like**

I want to make a alarm clock which having the functionality to  set the alaram 

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Riya14-dangra** [comment]
@Shweta2024 can you please assign this issue to me I want to work on it

**Comment by Shweta2024** [comment]
> @Shweta2024 can you please assign this issue to me I want to work on it

@Riya14-dangra sure!

**Comment by Shweta2024** [comment]
@Riya14-dangra what's the update?

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra what's the update?

@Shweta2024 I will complete it by 1st january 2023 because now my university exams are going on...
