### ISSUE TITLE
Implementing a stopwatch

### ISSUE THREAD

**Issue by ShivanshAr97** [Shweta2024/JavaScript-Projects#104]
**Describe the changes you'd like**
I would like to make a stopwatch, having features of starting count, stopping the count and to reset the stop watch.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@ShivanshAr97 what's the update?

**Comment by ShivanshAr97** [comment]
Will finish it by tomorrow

**Comment by Shweta2024** [comment]
> Will finish it by tomorrow

great!
