### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by nikhilsrv** [Shweta2024/JavaScript-Projects#105]
**Describe the changes you'd like**
A basic music player which will have buttons to play,pause the song.Button to play next/previous song.
There will aslo be a progress bar to show the progress of music.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by nikhilsrv** [comment]
@Shweta2024  @utkarsh006 Please assign me this task

**Comment by utkarsh006** [comment]
@nikhilsrv Work on issues which are not assigned to anyone.

**Comment by nikhilsrv** [comment]
sorry @utkarsh006  but I didn;t find any project or issue regarding it.

**Comment by utkarsh006** [comment]
@nikhilsrv Work on this [ISSUE](https://github.com/Shweta2024/JavaScript-Projects/issues/75). Comment there and it will be assigned to you.

**Comment by nikhilsrv** [comment]
@utkarsh006 @Shweta2024 please assign me this issue.

**Comment by Shweta2024** [comment]
@nikhilsrv assigned you!
