### ISSUE TITLE
Student Registration Form

### ISSUE THREAD

**Issue by Riya14-dangra** [Shweta2024/JavaScript-Projects#11]
**Describe the changes you'd like**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> hey @Shweta2024 can you please assign this issue to me I want to work on it

Make sure to complete the issue within a week & make a pr to the master branch.
