### ISSUE TITLE
Some Basic Converters 

### ISSUE THREAD

**Issue by Baron105** [Shweta2024/JavaScript-Projects#120]
**Describe the changes you'd like**
I would like to add three converters, for length, mass and temperature conversions.
Length - Meter, Feet, Miles, Inches, Centimeters and Kilometers 
Temperature - Celsius, Kelvin and Fahrenheit 
Mass - Pound, Ounces, Grams and Kilograms 

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by prehans** [comment]
Can you please assign this issue to me?

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like** I would like to add three converters, for length, mass and temperature conversions. Length - Meter, Feet, Miles, Inches, Centimeters and Kilometers Temperature - Celsius, Kelvin and Fahrenheit Mass - Pound, Ounces, Grams and Kilograms
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

assigned to @Baron105

**Comment by Shweta2024** [comment]
> Can you please assign this issue to me?

It has been assigned to @Baron105 as the issues are assigned on an FCFS basis. Kindly work on another issue.
