### ISSUE TITLE
The Dice Game

### ISSUE THREAD

**Issue by utkarshrohara** [Shweta2024/JavaScript-Projects#122]
Their will be some design changes that I'll like to add to the existing one.

**Comment by Shweta2024** [comment]
> Their will be some design changes that I'll like to add to the existing one.

what kind of changes to the design?

**Comment by utkarshrohara** [comment]
Background changes ,font and adding some space between dices

**Comment by Shweta2024** [comment]
@utkarshrohara what's the update?

**Comment by Shweta2024** [comment]
> I have done all the changes 5 days back and raised a PR request too. But I think there is some issue, because of which you are unable to see my changes.

fix the issue ASAP. Because I can't see any open pr of yours.👇
![image](https://user-images.githubusercontent.com/75883328/209517157-c021faba-7b9d-4a11-a94a-f6da6d0da529.png)

**Comment by Shweta2024** [comment]
@utkarshrohara any updates?
