### ISSUE TITLE
Countdown Timer Website

### ISSUE THREAD

**Issue by utkarsh006** [Shweta2024/JavaScript-Projects#13]
**Describe the changes you'd like**
- I would like to add a website that displays a timer using HTML,CSS,JS.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like**
> 
> * I would like to add a website that displays a timer using HTML,CSS,JS.
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

Make sure to complete the issue within a week & make a pr to the master branch.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Shweta2024 , i would really like to work on this issue for kwoc. Can u please assign me?

**Comment by Baron105** [comment]
@Shweta2024 can I work on this if its up for grab as of now? I'm participating in KWoC 2022.
Thanks

**Comment by Shweta2024** [comment]
> @Shweta2024 can I work on this if its up for grab as of now? I'm participating in KWoC 2022. Thanks

@Baron105 sure!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.
