### ISSUE TITLE
To do app with react

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [Shweta2024/JavaScript-Projects#133]
**Describe the project you'd like**
Iwill add the new todo web app built with react.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the project you'd like** Iwill add the new todo web app built with react.
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

@Naresh-chandanbatve there is already a todo app in this repo. Could you please tell me what new feature your todo app will have?
