### ISSUE TITLE
Grocery List

### ISSUE THREAD

**Issue by Suryansh1720001** [Shweta2024/JavaScript-Projects#140]
**Describe the changes you'd like**
This is a cool app using which you can keep a list of items you need to buy, you just have to add the items needed. You can also delete the item/items which are not required. You can add the items accordingly and buy or save them for future use cases.

Kindle, @utkarsh006 assign me this issue.

- [x] Read the contributing guideline
- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Suryansh1720001** [comment]
I have initiated a PR for this issue, Kindly check it.
Added PR #148

**Comment by Shweta2024** [comment]
> Hello @Shweta2024, I have initiated a PR for this issue, Kindly check it. Added PR #148 Thank you

@Suryansh1720001
reviewed & merged the pr!
