### ISSUE TITLE
Random Colour Generator

### ISSUE THREAD

**Issue by SattyamSamania** [Shweta2024/JavaScript-Projects#146]
**Describe the changes you'd like**

- I want to add a Random Colour Generator using Javascript. If you think that would be helpful kindly assign this issue to me. Thank You!

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like**
> 
> * I want to add a Random Colour Generator using Javascript. If you think that would be helpful kindly assign this issue to me. Thank You!
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

This project is already present in the repo.
