### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by utkarsh006** [Shweta2024/JavaScript-Projects#15]
**Describe the changes you'd like**

- The content in README file is repetitive.
- Will make the file concise and easier to read.
- Contributing under KWOC'22.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like**
> 
> * The content in README file is repetitive.
> * Will make the file concise and easier to read.
> * Contributing under KWOC'22.
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

Make sure to complete the issue within a week & make a pr to the master branch.
