### ISSUE TITLE
Random quote generator

### ISSUE THREAD

**Issue by ShivanshAr97** [Shweta2024/JavaScript-Projects#158]
**Describe the changes you'd like**

I would like to make a random quote generator along with the author of the quote, which will fetch the data from an API.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by ShivanshAr97** [comment]
@Shweta2024 please assign the issue to me

**Comment by Shweta2024** [comment]
@ShivanshAr97  Random quote generator is already there in this repo. Kindly work on a different issue.
