### ISSUE TITLE
Dancing Button Project

### ISSUE THREAD

**Issue by ansharora28** [Shweta2024/JavaScript-Projects#16]
**Describe the changes you'd like**

A button that moves away from you when you hover over it. Sort of a game where the button has exactly one job,not doing what it's supposed to do

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like** A clear and concise description of what you want to happen.
> 
> A button that moves away from you when you hover over it. Sort of a game where the button has exactly one job,not doing what it's supposed to do
> 
> * [ ]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

please tick-mark the above check box.

**Comment by ansharora28** [comment]
done

**Comment by Shweta2024** [comment]
> done

Make sure to complete the issue within a week & make a pr to the master branch
