### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by Suryansh1720001** [Shweta2024/JavaScript-Projects#162]
Hello @utkarsh006 @Shweta2024 

**Describe the changes you'd like**
I want to add the **Random Quote Generator** Platform. 

### Description
If you’re looking for some inspiration, we’ve got you covered. You’ll make an app that displays random famous quotes every time a button is pressed in this project. A quote from a prominent athlete, politician, or historical figure can be displayed:

To finish this project, you’ll need to know fundamental JavaScript syntaxes, such as variables, loops, and object literals. This project will allow you to practice fundamental JavaScript skills in a fun and effective way. It also includes a small interactive portfolio piece that you may use to demonstrate your knowledge of JavaScript.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.
- [x] Read the contributing guideline

Kindle assigns this to me.
Thank you

**Comment by Shweta2024** [comment]
@Suryansh1720001 Random quote generator is already there in this repo. Kindly work on a different issue.
