### ISSUE TITLE
Background Color Change Application

### ISSUE THREAD

**Issue by Suryansh1720001** [Shweta2024/JavaScript-Projects#163]
Hello @utkarsh006 @Shweta2024 

**Describe the changes you'd like**
I want to add the **Background Color Change Application**. 

### Description
In this app, the background color of the canvas changes when the user clicks on a button.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.
- [x] Read the contributing guideline

Kindle assigns this to me.
Thank you

**Comment by Shweta2024** [comment]
> Hello @utkarsh006 @Shweta2024 Kindle assigns this to me. Thank You

@Suryansh1720001  is this something like a random color generator or a random wallpaper generator?

**Comment by Suryansh1720001** [comment]
No, it is simple just change the color after clicking the button.
