### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by Suryansh1720001** [Shweta2024/JavaScript-Projects#168]
Hello @utkarsh006 @Shweta2024 

**Describe the changes you'd like**
I want to add the **Loan Calculator Application**. 

### Description
The main objective of this project is to calculate and displays the results for monthly payment, total payment, and total interest according to loan amount interest rate, and years to repay.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.
- [x] Read the contributing guideline

Kindle assigns this to me.
Thank you

**Comment by Shweta2024** [comment]
@Suryansh1720001  Don't tag the other guy. He is no more the mentor of this project.

**Comment by Suryansh1720001** [comment]
@Shweta2024, I'll take care of that.
