### ISSUE TITLE
Adding Ping Pong Game made using Html CSS and JS

### ISSUE THREAD

**Issue by gupta-ekansh** [Shweta2024/JavaScript-Projects#172]
**Describe the changes you'd like**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@gupta-ekansh this project is already present in the repo.Kindly work on any other issue.
