### ISSUE TITLE
Adding weather app using HTML CSS and JS

### ISSUE THREAD

**Issue by gupta-ekansh** [Shweta2024/JavaScript-Projects#173]
**Describe the changes you'd like**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@gupta-ekansh its already there in this repo! Kindly work on any other issues.
