### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by KSS-CHAITHANYA** [Shweta2024/JavaScript-Projects#176]
**Describe the changes you'd like**

Hi mam. I would like to make a small contribution to "Alarm Clock" project. 
I noticed that when the time reaches to "Set Alarm" Time, the alarm starts to ring.
I would like to add a snooze button to the alarm. So, that one can modify the alarm, 
either to a certain time before the "Set Alarm" or after the "Set Alarm".

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> **Describe the changes you'd like** A clear and concise description of what you want to happen.
> 
> Hi mam. I would like to make a small contribution to "Alarm Clock" project. I noticed that when the time reaches to "Set Alarm" Time, the alarm starts to ring. I would like to add a snooze button to the alarm. So, that one can modify the alarm, either to a certain time before the "Set Alarm" or after the "Set Alarm".
> 
> * [ ]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

sure, go ahead!
make sure to read the contributing guidelines before starting to work on the issue and checkmark above the box.

**Comment by KSS-CHAITHANYA** [comment]
Sure
Thank you
