### ISSUE TITLE
Make attractive UI for BMI Calculator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#2]
Make an attractive UI for [BMI-calculator](https://github.com/Shweta2024/JavaScript-Projects/tree/main/BMI-calculator), you can do the following :- 

- align all at the center
- change the font style
- change the background color

**Comment by dikshapadi** [comment]
Hey @Shweta2024 , could you please assign this task to me as I am willing to work on this.
Thank you :)

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Shweta2024 , i would really like to work on this issue for kwoc. Can u please assign me?

**Comment by Shweta2024** [comment]
> Hey @Shweta2024 can you please assign this task to me I want to work on it

Hey, @Riya14-dangra please complete your previous issue first, because at a time you can work on ONLY ONE issue.

**Comment by Shweta2024** [comment]
> > > Hey @Shweta2024 can you please assign this task to me I want to work on it
> > 
> > 
> > Hey, @Riya14-dangra please complete your previous issue first, because at a time you can work on ONLY ONE issue.
> 
> I am almost done with that one within one hour I will going to make a PR

Great, but please comment on any new issue for assigning it to you, only when you have created the pr for the previous issue. Because other contributors should also be given chance, isn't it?I hope you get it :)
