### ISSUE TITLE
Make an attractive UI for calculator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#22]
**Describe the changes you'd like**

For the project [Calculator](https://github.com/Shweta2024/JavaScript-Projects/tree/master/Calculator), make an attractive UI.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Riya14-dangra** [comment]
hey @Shweta2024 can you please assign this issue to me under kwoc2022

**Comment by Shweta2024** [comment]
> hey @Shweta2024 can you please assign this issue to me under kwoc2022

Assigned you @Riya14-dangra .
Make sure to complete it within a week & make pr to the master branch.
