### ISSUE TITLE
Weather app UI improvement

### ISSUE THREAD

**Issue by PritamSarbajna** [Shweta2024/JavaScript-Projects#23]
**Describe the changes you'd like**
I want to improve the UI of the page where we are submitting the city name because it has no styles yet.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@PritamSarbajna Go ahead!
Make sure to complete the task within a week & create pr for the master branch.

**Comment by PritamSarbajna** [comment]
@Shweta2024 thank you so much 🙌
have you assigned me under KWoC ?

**Comment by Shweta2024** [comment]
> @Shweta2024 thank you so much 🙌 have you assigned me under KWoC ?

Yes, all the issues are getting assigned under KWOC.
