### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by NiharikaSharma18** [Shweta2024/JavaScript-Projects#26]
**Describe the changes you'd like**

- [ ] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Riya14-dangra** [comment]
Hey @Shweta2024 can you please assign this task to me under kwoc2022.I want to work on it
