### ISSUE TITLE
add message in BMI Calculator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#3]
show messages for each of the BMI of a person:- 
- If the BMI is less than 18.5, it falls within the underweight range.
- If the BMI is 18.5 to <25, it falls within the healthy weight range.
- If the BMI is 25.0 to <30, it falls within the overweight range.
- If the BMI is 30.0 or higher, it falls within the obesity range.
show any of the above message to the user based on their BMI

**Comment by SattyamSamania** [comment]
Hey @Shweta2024 can you please assign this issue to me under KWOC

**Comment by Shweta2024** [comment]
> Hey @Shweta2024 can you please assign this issue to me under KWOC

you can work on ONE issue at a time.
Please complete your previous one first.

**Comment by chhavitekriwal** [comment]
Kindly assign. @Shweta2024

**Comment by Shweta2024** [comment]
> Kindly assign. @Shweta2024

Make sure to complete the issue within a week & make a pr to the master branch.
