### ISSUE TITLE
Add rock paper scissors game

### ISSUE THREAD

**Issue by Aarize29** [Shweta2024/JavaScript-Projects#30]
**The Game will have very good UI with sound effect**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@Aarize29 Go ahead! you can work on this issue.
Make sure to complete the task within a week & make a pr to the master branch

**Comment by Aarize29** [comment]
> @Aarize29 Go ahead! you can work on this issue. Make sure to complete the task within a week & make a pr to the master branch

Okay Ma'am

**Comment by Aarize29** [comment]
I have opened a pull request  please check!!!!

**Comment by Shweta2024** [comment]
> I have opened a pull request please check!!!!

checked & merged✅
