### ISSUE TITLE
SignUp Login Form

### ISSUE THREAD

**Issue by Riya14-dangra** [Shweta2024/JavaScript-Projects#31]
**Describe the changes you'd like**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

Responsive Signup and login page of slider as if you are new user then you can sign up and if you are already a user then login in . Attributes including name email and password and login with google or other social media platforms

**Comment by Riya14-dangra** [comment]
hey @Shweta2024 can you please assign this task to me. I want to work on it under kwoc2022!!

**Comment by Shweta2024** [comment]
@Riya14-dangra please tick mark the check-box

**Comment by Riya14-dangra** [comment]
> @Riya14-dangra please tick mark the check-box and provide a description of your issue (like what all fields you want to involve in the signup page) in the description of the issue.

I ticked marked it .
