### ISSUE TITLE
random color  generator

### ISSUE THREAD

**Issue by NiharikaSharma18** [Shweta2024/JavaScript-Projects#34]
**Describe the changes you'd like**

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@NiharikaSharma18 please tick mark the checkbox.

**Comment by Shweta2024** [comment]
@NiharikaSharma18 Make sure to complete the task within a week & make a pr to the master branch.
