### ISSUE TITLE
Assign the project

### ISSUE THREAD

**Issue by Pinkuagrawal28** [Shweta2024/JavaScript-Projects#36]
**Describe the changes you'd like**
I want to work on this project and i will like to improve the readme file and other codes.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@Pinkuagrawal28 can you please specify which code you want to improve?
Also, mention all the changes that you want to do in the README.
