### ISSUE TITLE
Create a piano using js

### ISSUE THREAD

**Issue by Koustavjr** [Shweta2024/JavaScript-Projects#38]
**Describe the changes you'd like**
I would like to create a simple piano using javascript.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Koustavjr** [comment]
@Shweta2024 @utkarsh006 can u please assign me this issue?

**Comment by Shweta2024** [comment]
> @Shweta2024 @utkarsh006 can u please assign me this issue?

@Koustavjr assigned you!
Make sure to complete the task within a week & make a pr to the master branch.
