### ISSUE TITLE
Javascript pairs game

### ISSUE THREAD

**Issue by Pinkuagrawal28** [Shweta2024/JavaScript-Projects#39]
**Describe the changes you'd like**
A javascript game which tests memory.
There will be some cards and the users will have to find all the matching pairs.
we have certain number of guesses allowed before the game ends.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
@Pinkuagrawal28 assigned you!
Make sure to complete the task within a week & make the pr to the master branch.

**Comment by Pinkuagrawal28** [comment]
I have Completed my project and created a pull request please take a look at it. Also, give me feedback on my created issue as I have a confusion about guidelines related to the branch.

**Comment by Shweta2024** [comment]
> I have Completed my project and created a pull request please take a look at it. Also, give me feedback on my created issue as I have a confusion about guidelines related to the branch.

@Pinkuagrawal28 please make the pr from a different branch.

**Comment by Pinkuagrawal28** [comment]
@Shweta2024  didi I have made a pull request from a different branch take a look at that.

**Comment by Shweta2024** [comment]
> @Shweta2024 didi I have made a pull request from a different branch take a look at that.

sure
