### ISSUE TITLE
Add more functionalities to Calculator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#4]
In [Calculator](https://github.com/Shweta2024/JavaScript-Projects/tree/main/Calculator) add functionalities to :- 
- display difference of two numbers
- multiplication
- division
- and modulus

**Comment by rhinoxD** [comment]
Please assign

**Comment by Shweta2024** [comment]
> Please assign

Make sure to complete the issue within a week & make a pr to the master branch.
