### ISSUE TITLE
square root,cube root,square and cube in the calculator

### ISSUE THREAD

**Issue by Abbashozefa** [Shweta2024/JavaScript-Projects#41]
**Describe the changes you'd like**

The Calculator isn't having a direct function to find a square,cube,cube root and square root.
Adding these functionalities in the PR.

- [*] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by utkarsh006** [comment]
@Abbashozefa Do the given below tasks : 
- Mention the issue number in the PR template.
- Comment what you have done in your JS code.
- Add working video in the PR template displaying your changes.

**Comment by Abbashozefa** [comment]
Okay, will do it right away
