### ISSUE TITLE
Project: JavaScript-Projects repo    Issue: Remaking the README.md (Simultaneously the deployed github-pages)

### ISSUE THREAD

**Issue by Sapt-pal** [Shweta2024/JavaScript-Projects#45]
**A brief description of my idea**

## The readme page needs a revamp with a stronger implementation.

-    If we want it to act as both the **readme page** for the github repo _as well as_ the **landing page** for the deployment, I would like to have the entire thing in HTML,CSS and JS only.

Or else

-    We can have an identical implementation of the markdown page in the deployed page using the above trio only.

##### (Will ping back with a suggested layout and design)

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by utkarsh006** [comment]
@Sapt-pal So basically, you are making to make website for this repo using GH Pages?

**Comment by Sapt-pal** [comment]
> @Sapt-pal So basically, you are making to make website for this repo using GH Pages?

@utkarsh006

Yeah so I saw that a placeholder was already implemented, I want to complete it up and (as @Shweta2024 suggested) keep updating with all new changes in the project over the course of the KWoC.

**Comment by Shweta2024** [comment]
> > @Sapt-pal So basically, you are making to make website for this repo using GH Pages?
> 
> @utkarsh006
> 
> Yeah so I saw that a placeholder was already implemented, I want to complete it up and (as @Shweta2024 suggested) keep updating with all new changes in the project over the course of the KWoC.

@Sapt-pal as I suggested that you can work on this pr a few days prior to the end of KWOC, because by that time we'll have all the projects.
Otherwise each time someone will add a new project and you'll have to create a pr.
So to avoid that repetition of the same kind of pr, I would suggest you work on this issue somewhat prior to the end of KWOC.
