### ISSUE TITLE
A Ping Pong game

### ISSUE THREAD

**Issue by nikhilsrv** [Shweta2024/JavaScript-Projects#49]
Ping Pong game using HTML,CSS and JAVASCRIPT.

Features:
- Game will be between computer and user.
- Scores will be calculated
- Timer will be set
- At the end of time duration winner will be displayed.

A screenshot of game is:
![Screenshot (478)](https://user-images.githubusercontent.com/108658668/206857541-feece99a-04bd-4fda-95b3-41b9ac97bb5d.png)

**Comment by nikhilsrv** [comment]
Please assign me this task?

**Comment by Shweta2024** [comment]
@nikhilsrv use the **Issue Template** for creating a new issue. 
I have already told this to all the contributors who have joined the discord channel, to use the default issue template and to provide a description of the project.
Please follow the guidelines.

**Comment by nikhilsrv** [comment]
@Shweta2024 updated the comment.Is it fine?
