### ISSUE TITLE
JS + CSS Clock

### ISSUE THREAD

**Issue by royalpinto007** [Shweta2024/JavaScript-Projects#53]
I have added a new project, it's a simple clock made using HTML, CSS, JavaScript.

Here's the link to my pull request- https://github.com/Shweta2024/JavaScript-Projects/pull/51

**Comment by Shweta2024** [comment]
> I have added a new project, it's a simple clock made using HTML, CSS, JavaScript.
> 
> Here's the link to my pull request- #51

@royalpinto007 from the next time, make sure to raise an issue before making the pr.

**Comment by Suryansh1720001** [comment]
Hello @utkarsh006
Kindle assign this issue to me
Thank you

**Comment by utkarsh006** [comment]
@royalpinto007 You can't close the issue on your own. Let others work on the issue. You were given appropriate time to complete that.

**Comment by royalpinto007** [comment]
I understand @utkarsh006, but why is the issue showing me again, even though it has been assigned to someone else?
Also, I created the issue. I admit that I was inactive for a while, but that doesn't mean you can assign my issue to someone else right?

**Comment by utkarsh006** [comment]
@royalpinto007 Contributors like you won't respond to the Mentor's review properly, neither they will do their assigned tasks on time. Kindly suggest me what should I have done?

**Comment by utkarsh006** [comment]
@royalpinto007 You are not the mentor or maintainer here to close any issue. This is the second time. @Shweta2024 Kindly see this.

**Comment by Shweta2024** [comment]
@royalpinto007 this is not professional behavior. You have been given sufficient time to complete the task, but you didn't.
 It's clearly mentioned in the contributing guidelines that you must complete the task within a week and if you fail to do that then it will be assigned to someone else.
Kindly don't close any issue on your own.

**Comment by royalpinto007** [comment]
I'm sorry, but is there any option for me to opt out from this? @utkarsh006 @Shweta2024
