### ISSUE TITLE
Attractive UI for Bad-Button

### ISSUE THREAD

**Issue by sakshipratap** [Shweta2024/JavaScript-Projects#56]
**Describe the changes you'd like**
Replacing black-grey background with an illusory screen with some funky text making overall display attractive.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by utkarsh006** [comment]
@sakshipratap You are doing the changes in which project?

**Comment by sakshipratap** [comment]
> @sakshipratap You are doing the changes in which project?

Yes. I'm working on it.

**Comment by sakshipratap** [comment]
> @sakshipratap You are doing the changes in which project?

On the project "Bad-Button", in which there is a button which is moving in a random direction when we take our cursor close to it.

**Comment by sakshipratap** [comment]
Kindly assign this project to me.
