### ISSUE TITLE
BMI calculator UI improvement

### ISSUE THREAD

**Issue by srj06** [Shweta2024/JavaScript-Projects#58]
Want to add some styling and Navbar to make it look attractive.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> Want to add some styling and Navbar to make it look attractive.
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

please explain, what changes in the styling.

**Comment by srj06** [comment]
Styling means giving colorful background to the page  using CSS.

**Comment by Shweta2024** [comment]
> Styling means giving colorful background to the page using CSS.

Ok, go ahead!
Try to make a better UI

**Comment by Shweta2024** [comment]
> Want to add some styling and Navbar to make it look attractive.
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

there is already an existing issue on this #60
So, I'm closing this issue.
Kindly select any other issue to work on.
