### ISSUE TITLE
Dictionary

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#65]
**Describe the changes you'd like**

Make a dictionary app, such that it can take a word as input and give its meaning as output.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by ShivanshAr97** [comment]
I would like to work for this issue
from KWOC

**Comment by nikhilsrv** [comment]
@Shweta2024  please assign me this task

**Comment by madeupgalaxy** [comment]
I want to take up this issue @Shweta2024 
Earlier I worked on Twitter tweet box#67, Now I want to take up a harder challenge

**Comment by Shweta2024** [comment]
@madeupgalaxy assigned you!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by Shweta2024** [comment]
@nikhilsrv @ShivanshAr97 please complete your previous task first.

**Comment by madeupgalaxy** [comment]
> @madeupgalaxy assigned you!
> make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

Thankyou.
Will do my best 😄
