### ISSUE TITLE
File Uploader

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#66]
**Describe the changes you'd like**

Make an application that would be capable of uploading files from your system and will have a progress bar.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by coderboy-yash** [comment]
hey I think I can  solve this issue can you please assign this to me.

**Comment by Shweta2024** [comment]
> hey I think I can solve this issue can you please assign this to me.

@coderboy-yash assigned you!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by Shweta2024** [comment]
@coderboy-yash what's the update?

**Comment by himanshu1221** [comment]
> @coderboy-yash what's the update?

can i work o this issue ?

**Comment by Shweta2024** [comment]
> > @coderboy-yash what's the update?
> 
> can i work on this issue ?

sure go ahead!
make sure to read the [contributing guidelines](https://github.com/Shweta2024/JavaScript-Projects/blob/master/Guidelines.md) first.

**Comment by himanshu1221** [comment]
> > > @coderboy-yash what's the update?
> > 
> > 
> > can i work on this issue ?
> 
> sure go ahead! make sure to read the [contributing guidelines](https://github.com/Shweta2024/JavaScript-Projects/blob/master/Guidelines.md) first.

Hey there isno folder that name starts with F
