### ISSUE TITLE
Twitter Tweet box

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#67]
**Describe the changes you'd like**

Create a Twitter tweet box that will have a word limit of 100 words, such that if the user enters more than 100 words then it will cut the rest words.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by madeupgalaxy** [comment]
I want to work on this issue. I'm coming from KWOC 2022

**Comment by Shweta2024** [comment]
> I want to work on this issue. I'm coming from KWOC 2022

@madeupgalaxy sure go ahead!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by madeupgalaxy** [comment]
Okay, Thankyou
