### ISSUE TITLE
Wallpaper Generator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#68]
**Describe the changes you'd like**

Make an application that can generate a random wallpaper.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by nikhilsrv** [comment]
@Shweta2024 can you assign me this issue?

**Comment by Shweta2024** [comment]
> @Shweta2024 can you assign me this issue?

@nikhilsrv assigned you!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.
