### ISSUE TITLE
Email validation checker

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#69]
**Describe the changes you'd like**

Make an application that can check if the entered email is in the correct format.
If it's in the correct format then display a suitable message stating that it's in the correct format otherwise ask them to enter the email in the correct format.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by nikhilsrv** [comment]
@Shweta2024  can you assign me this issue?

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by Shweta2024** [comment]
> Can i work in this issue?

@harsitagarwalla187 sure go ahead!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by harsitagarwalla187** [comment]
This issue was assigned to me?

**Comment by harsitagarwalla187** [comment]
![Screenshot 2022-12-15 120707](https://user-images.githubusercontent.com/84774840/207790574-a615869b-de21-4167-8338-b78a194bb8c1.png)
