### ISSUE TITLE
Quote Generator 

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#7]
Make use of API to create a random quote generator.

**Comment by Shweta2024** [comment]
> Assign it to me.

you can work on ONE issue at a time.
Please complete your previous one first.

**Comment by rhinoxD** [comment]
I have to make this from scratch?

**Comment by rhinoxD** [comment]
I've made it with both vanilla javascript and react which one would you prefer?

**Comment by rhinoxD** [comment]
Alright
