### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#70]
**Describe the changes you'd like**

Make an application that can generate random passwords for the user.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by Koustavjr** [comment]
@Shweta2024 can u please assign me this issue?

**Comment by Shweta2024** [comment]
> @Shweta2024 can u please assign me this issue?

@Koustavjr assigned!

**Comment by Shweta2024** [comment]
great work @Koustavjr 
LGTM🎉
