### ISSUE TITLE
Ludo Game

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#71]
**Describe the changes you'd like**

Create a ludo game.

Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by Rishav1707** [comment]
Shall I work on this issue?? @Shweta2024

**Comment by Shweta2024** [comment]
> Shall I work on this issue?? @Shweta2024

@Rishav1707 sure go ahead!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by utkarsh006** [comment]
@Rishav1707 It's been 3 days what's the update?

**Comment by Rishav1707** [comment]
In process...

**Comment by Rishav1707** [comment]
Within a week I'll report to you.
