### ISSUE TITLE
Password's Strength checker

### ISSUE THREAD

**Issue by Shweta2024** [Shweta2024/JavaScript-Projects#72]
**Describe the changes you'd like**

Create an application that can take a password as input and will check its strength and will display a message to the user stating if its 
a strong password or not.
If it's not a strong password then it should also show the user the changes that he/she to make a strong password.

Requirements for a strong password:- 
- must contain lowercase characters
- must contain uppercase characters
- must contain digits
- must contain special characters
- must be of at least 8 size 

### Required Tech stacks:-

- HTML
- CSS
- JavaScript

**Comment by ShivanshAr97** [comment]
I would like to work for this issue

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by Shweta2024** [comment]
> I would like to work for this issue For KWOC

@ShivanshAr97 assigned you!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by ShivanshAr97** [comment]
Yes thanks

**Comment by harsitagarwalla187** [comment]
![0](https://user-images.githubusercontent.com/84774840/207302170-39a217a8-6368-4cb0-82ca-1b0e73541640.png)
![1](https://user-images.githubusercontent.com/84774840/207302179-6222a807-ff11-4f96-aa30-2b269e1fa1e9.png)
Please have a look at my work!
