### ISSUE TITLE
Adding  footer to the BMI calculator

### ISSUE THREAD

**Issue by srj06** [Shweta2024/JavaScript-Projects#73]
I want to add a footer to the page. 

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by maddy020** [comment]
How to run this project on local machine as there is no readme file here?

**Comment by chandakanup** [comment]
I want to work on this project. Will you pls assign this task to me

**Comment by Shweta2024** [comment]
@chandakanup  assigned you!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.

**Comment by Shweta2024** [comment]
@chandakanup what's the update?
