### ISSUE TITLE
sliding cards 

### ISSUE THREAD

**Issue by Janhvi52** [Shweta2024/JavaScript-Projects#74]
can i add a project image slider which iz mainly focused on js

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> can i add a project image slider which iz mainly focused on js
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

@Janhvi52  sure go ahead!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.
