### ISSUE TITLE
Theme Clock

### ISSUE THREAD

**Issue by Janhvi52** [Shweta2024/JavaScript-Projects#75]
can i add a project called theme clock to ur repo

- [✔️ ] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> can i add a project called theme clock to ur repo
> 
> * [✔️ ] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

first, complete your previous task.
At a time you can work only on one issue.

**Comment by Shweta2024** [comment]
> can i add a project called theme clock to ur repo
> 
> * [✔️ ] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

also please add a description to the issue.

**Comment by nikhilsrv** [comment]
@utkarsh006 please assign me this task.Should I make a theme clock or a music player?

**Comment by utkarsh006** [comment]
@nikhilsrv What do you think?

**Comment by Janhvi52** [comment]
> > can i add a project called theme clock to ur repo
> > 
> > * [✔️ ] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.
> 
> first, complete your previous task. At a time you can work only on one issue.

i've created a pr for the previous one, kindly review it
Now can i work on this issue?
