### ISSUE TITLE
Create a To do list website 

### ISSUE THREAD

**Issue by YadnikaDabhade** [Shweta2024/JavaScript-Projects#8]
Can you please assign this to me?
I want to work on this issue.

**Comment by Shweta2024** [comment]
> Can you please assign this to me? I want to work on this issue.

Make sure to complete the issue within a week & make a pr to the master branch.

**Comment by YadnikaDabhade** [comment]
Mam I have send another pull request to your master branch please have a look , please let mi know if it is okk.

**Comment by Shweta2024** [comment]
> Mam I have send another pull request to your master branch please have a look , please let mi know if it is okk.

@YadnikaDabhade I can't see any of your pr to my master branch.
Can you please drop the link of that pr here in the comment

**Comment by Shweta2024** [comment]
@YadnikaDabhade it's been a week, please complete your task by today.

**Comment by YadnikaDabhade** [comment]
> @YadnikaDabhade it's been a week, please complete your task by today.

Mam I have already completed my task of creating todo list website , and also you have merged my pr .

**Comment by YadnikaDabhade** [comment]
Mam ,
I have already completed my task of creating todo list website ,also you
have merged my pr..
