### ISSUE TITLE
Hex Color Application

### ISSUE THREAD

**Issue by Suryansh1720001** [Shweta2024/JavaScript-Projects#83]
Hello @Shweta2024  @utkarsh006 
Please assign this issue to me.
Thank you

**Comment by Shweta2024** [comment]
> Hello @Shweta2024 @utkarsh006 Please assign this issue to me. Thank you

@Suryansh1720001 kindly use the issue template for this issue and write a description for the issue.

**Comment by DHRUVKHANDELWAL00** [comment]
@utkarsh006  assign me please

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Assigned. No need of saying please in Open source projects. Thank You.

**Comment by Shweta2024** [comment]
> > Hello @Shweta2024 @utkarsh006 Please assign this issue to me. Thank you
> 
> @Suryansh1720001 kindly use the issue template for this issue and write a description for the issue.

@utkarsh006 the issue template isn't complete also it doesn't have a description, how can you assign this?
I'm not getting what this issue is doing. Also, @DHRUVKHANDELWAL00 has even raised a pr on this.
