### ISSUE TITLE
Create a kindergarten website

### ISSUE THREAD

**Issue by Riya14-dangra** [Shweta2024/JavaScript-Projects#88]
**Describe the changes you'd like**

I school of small kids is very interesting having various funny XD poster and drawing. As this website is the website of small kids school having section of various activities of school, teachers of school, about the school and contact section to get contact with school. So here I want to implement more css and make it more attractive UI for website 

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Riya14-dangra** [comment]
> **Describe the changes you'd like** A clear and concise description of what you want to happen.
> 
> I school of small kids is very interesting having various funny XD poster and drawing. As this website is the website of small kids school having section of various activities of school, teachers of school, about the school and contact section to get contact with school. So here I want to implement more css and make it more attractive UI for website
> 
> * [x]  I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

@utkarsh006 & @Shweta2024 can you please assign this issue to me under kwoc2022 i want to work on it

**Comment by Riya14-dangra** [comment]
@Shweta2024 should I go for it

**Comment by Shweta2024** [comment]
> @Shweta2024 should I go for it

sure!
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.
