### ISSUE TITLE
Create a hangman game

### ISSUE THREAD

**Issue by salted0dreams** [Shweta2024/JavaScript-Projects#90]
**Describe the changes you'd like**

Create a Hangman game

Required Tech stacks:-
-  HTML
- CSS
- JavaScript

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Shweta2024** [comment]
> I would like to work on this issue. Please assign it to me.

@salted0dreams 
please use the Issue template for creating the issue also add a description for the issue.

**Comment by salted0dreams** [comment]
Is this good?

**Comment by Shweta2024** [comment]
> Is this good? @Shweta2024

yeah!
I have assigned you the issue.
make sure to read the contributing guidelines before starting to work on the issue and complete the task within a week.
