### ISSUE TITLE
To put buttons inside calculator

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [Shweta2024/JavaScript-Projects#95]
I would like to change UI of calculator as '0','00','.','=' buttons are flowing out of calculator box.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by DHRUVKHANDELWAL00** [comment]
![image](https://user-images.githubusercontent.com/99539203/208126505-6e852b14-c48a-4773-8b5d-bb1535ea4af3.png)

**Comment by maddy020** [comment]
Please assign this issue to me 
I have resolved the issue and going to create a PR

**Comment by DHRUVKHANDELWAL00** [comment]
@maddy020  i literally created this issue to work on. Please create you own issue.

**Comment by maddy020** [comment]
> @maddy020 i literally created this issue to work on. Please create you own issue.

I am so sorry bro 
I haven't seen your reply over the message
But you can still contribute to this issue and create your own PR

I am creating new issue you can also contribute to that one which is also beginner friendly

**Comment by Shweta2024** [comment]
@DHRUVKHANDELWAL00 @maddy020 I haven't assigned this issue to anyone of you.

**Comment by DHRUVKHANDELWAL00** [comment]
@Shweta2024 can u assign me this task then?

**Comment by utkarsh006** [comment]
@DHRUVKHANDELWAL00 Assigned to you.
