### ISSUE TITLE
Guess The Number

### ISSUE THREAD

**Issue by Pinkuagrawal28** [Shweta2024/JavaScript-Projects#96]
**Describe the changes you'd like**
In this Game we have to guess the number between 1 to 100 correctly we can set the difficulty level by adjusting the number of chances. Also The user will have hints in each guess telling them whether they guessed too high or too low.

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by utkarsh006** [comment]
@Pinkuagrawal28 What's the update?

**Comment by Pinkuagrawal28** [comment]
I have almost completed the game and now I am adding an option for choosing a level by selecting the number of chances by the user.

**Comment by Shweta2024** [comment]
> @Shweta2024 didi, I have almost completed the game and now I am adding an option for choosing a level by selecting the number of chances by the user.

ok @Pinkuagrawal28 
thanks for sharing the updates
