### ISSUE TITLE
Make calculator responsive

### ISSUE THREAD

**Issue by maddy020** [Shweta2024/JavaScript-Projects#99]
**Describe the changes you'd like**

At different screen sizes , keys go outside the container 

![i](https://user-images.githubusercontent.com/103564105/208237843-4017e851-7cf0-414a-afbe-d90eeea82354.PNG)

It must looks like 
![after](https://user-images.githubusercontent.com/103564105/208237886-364ca627-7329-42bf-ac2a-21991e9b6ac9.PNG)

- [x] I follow the [Contributing Guideline](https://github.com/Shweta2024/JavaScript-Projects/blob/master/ContributingGuidelines.md) of JavaScript-Projects.

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Shweta2024

**Comment by YashAw12** [comment]
hey @Shweta2024 i can use bootstrap( using column class) to make it responsive quickly. Please assign it to me!

**Comment by Shweta2024** [comment]
@Rishav1707 @YashAw12 
the same issue has been assigned to someone else!
